"""Complete-episode on-policy collection, validation-only checkpoint selection."""
from copy import deepcopy
from pathlib import Path
from time import perf_counter
import platform

import numpy as np
import torch
import networkx as nx

from ..config import fingerprint
from ..env.leo_env import LeoEnv, generate_cpu_capacities
from ..evaluation.evaluator import evaluate_policy
from ..tasks.task_generator import generate_task_trace
from ..topology.topology_cache import generate_topology
from ..utils.io import save_csv, save_json, save_yaml
from .ppo_agent import PPOAgent
from .rollout_buffer import RolloutBuffer, Transition
from .diagnostics import add_counts, decision_metrics
from .episode_scenarios import SCENARIO_SCHEMA, episode_configuration, episode_inputs
from ..utils.progress import EpisodeProgress, device_summary, gpu_memory, duration_text, metric_text, outcome_text


def train_ppo(config, output_directory, resume=None, progress=None, log_interval_seconds=10.0, console_log=None):
    output = Path(output_directory).resolve()
    def report(message):
        if progress:
            progress(message)

    if output.exists() and any(output.iterdir()):
        raise ValueError("Training output is nonempty; use a new directory")
    report("[SETUP] Initializing model / loading checkpoint ... | result_dir=%s | requested_device=%s CUDA_available=%s" % (
        output, config.get("rl", {}).get("device", "auto"), torch.cuda.is_available()))
    agent, state = PPOAgent.load(resume, config.get("rl", {}).get("device"), True) if resume else (PPOAgent(config), {})
    if resume and fingerprint(agent.config) != fingerprint(config):
        # Device and target update count may change, but architecture/scales/seeds/objective may not.
        old, new = deepcopy(agent.config), deepcopy(config)
        for resolved in (old, new):
            for field in ("device", "updates"):
                resolved.get("rl", {}).pop(field, None)
        if fingerprint(old) != fingerprint(new):
            raise ValueError("Resume configuration changed beyond device/updates")
        agent.settings["updates"] = config.get("rl", {}).get("updates", agent.settings["updates"])
        agent.config = deepcopy(config)
    settings = agent.settings
    if resume and settings["randomize_episodes"] and state.get("training_scenario_schema") != SCENARIO_SCHEMA:
        raise ValueError("Checkpoint lacks the matching randomized episode protocol; start a new training directory")
    if settings["updates"] <= agent.update_count:
        raise ValueError("Target updates must exceed the checkpoint update count")
    report("[DEVICE] " + device_summary(agent.device, config.get("rl", {}).get("device", "auto")))
    report("[DEVICE SPLIT] rollout=%s PPO_update=%s | synchronized weights after every update" % (
        agent.rollout_model.device, agent.device))
    report("[TRAIN] model=%s init_seed=%s updates=%s->%s episodes/update=%s router=%s node_mask=%s allocation=%s" % (
        agent.name, settings["seed"], agent.update_count, settings["updates"], settings["episodes_per_update"],
        config["routing"]["mode"], settings["use_mask"], config["resource"]["allocation"]))
    report("[REPRESENTATION] features=%s schema=%s node_dim=%s destination_dim=%s graph_neighbors=%s parameters=%s" % (
        settings["feature_set"], agent.features.schema, agent.features.node_dim, agent.features.destination_dim,
        settings["graph_neighbors"], sum(p.numel() for p in agent.model.parameters())))
    report("[INFO] Simulator/graph routing runs on CPU. FPS = completed environment slots / wall seconds; "
           "rollout FPS excludes optimizer and validation. ETA is an estimate from completed updates.")
    report("[LEARNING] action=computing_satellite | value_scale=%s | no completion-time prior; "
           "router runs after node selection" % settings["value_scale"])
    report("[SCENARIO PROTOCOL] mode=%s roots=%s | validation stays fixed; episode inputs are independent of policy RNG" % (
        "randomized_by_episode" if settings["randomize_episodes"] else "fixed_replay",
        settings["train_seeds"]))
    report("[FILES] metrics=%s | checkpoints=%s | curves generated by scripts/plot_training.py" % (output, output))
    report("[SETUP] Generating topology ...")
    configured = agent.configure_environment(config)
    topology = generate_topology(configured, progress=progress, log_interval_seconds=log_interval_seconds)
    output.mkdir(parents=True, exist_ok=True)
    save_yaml(output / "resolved_config.yaml", config)
    save_json(output / "training_manifest.json", {"schema": 1, "config_sha256": fingerprint(config),
              "feature_schema": agent.features.schema,
              "feature_set": settings["feature_set"], "graph_neighbors": settings["graph_neighbors"],
              "node_dim": agent.features.node_dim, "destination_dim": agent.features.destination_dim,
              "parameter_count": sum(p.numel() for p in agent.model.parameters()),
              "graph_gate_bias": settings["graph_gate_bias"] if agent.model.is_gated else None,
              "critic_encoding": "own_node_mlp" if agent.model.is_gated else settings["encoder"],
              "action_space": "computing_satellite", "router_mode": configured["routing"]["mode"],
              "value_scale": settings["value_scale"],
              "node_mask": settings["use_mask"], "reservation_is_guarantee": False,
              "torch": str(torch.__version__), "numpy": np.__version__, "python": platform.python_version(),
              "device": str(agent.device), "cuda_runtime": torch.version.cuda,
              "rollout_device": str(agent.rollout_model.device),
              "gpu": torch.cuda.get_device_name(agent.device) if agent.device.type == "cuda" else None,
              "gpu_used": agent.device.type == "cuda", "cuda_available": torch.cuda.is_available(),
              "log_interval_seconds": log_interval_seconds,
              "console_log": str(Path(console_log).resolve()) if console_log else None,
              "fps_definition": "completed environment slots / wall seconds; rollout includes drain, excludes optimizer/validation",
              "resume_from": str(Path(resume).resolve()) if resume else None,
              "train_seeds": settings["train_seeds"], "validation_seeds": settings["validation_seeds"],
              "training_scenario_schema": SCENARIO_SCHEMA,
              "randomize_episodes": settings["randomize_episodes"],
              "episode_randomness": "root + absolute episode index + domain; continuation uses checkpoint episode_count",
              "topology_file_role": "fixed validation/reference topology; randomized training epochs saved in episode_scenarios/",
              "selection": "maximize mean validation episode reward; never test-set performance",
              "ppo_action": "satellite-only autoregressive batch; summed node log probabilities; one physical-slot ratio",
              "ppo_evaluation": "packed graph/task minibatches; frozen sampled prefixes; unchanged joint PPO objective",
              "truncation": "environment drain censorship is a terminal finite-horizon outcome, bootstrap=0"})
    report("[SETUP] Saving topology and training manifest ...")
    topology.save(output / "topology.npz")
    episode_count = state.get("episode_count", 0)
    best_reward = state.get("best_validation_reward", None)
    best_update = state.get("best_update", None)
    if resume:
        # This keeps the previous best available in a new resume directory.
        old_best = Path(resume).parent / "best.pt"
        old_best_update = (torch.load(old_best, map_location="cpu", weights_only=True).get("update_count")
                           if old_best.exists() else None)
        if old_best.exists() and old_best_update == best_update:
            from shutil import copy2
            copy2(old_best, output / "best.pt")
        else:
            # A historical checkpoint may predate the source directory's best.
            # Do not carry a model trained after the resumed checkpoint forward.
            best_reward, best_update = None, None
    episodes, updates, validation = [], [], []
    started = perf_counter()
    session_steps, completed_updates = 0, 0
    while agent.update_count < settings["updates"]:
        update_started = perf_counter()
        buffer = RolloutBuffer()
        next_update = agent.update_count + 1
        collection_seconds = 0.0
        for episode_in_update in range(settings["episodes_per_update"]):
            episode_config, scenario = episode_configuration(configured, settings, episode_count)
            seed = scenario["episode_seed"]
            label = "ROLLOUT u=%s/%s ep=%s/%s seed=%s" % (
                next_update, settings["updates"], episode_in_update + 1, settings["episodes_per_update"], seed)
            report("[%s] episode=%s/%s | preparing task trace/reset ..." % (
                label, episode_count + 1, settings["updates"] * settings["episodes_per_update"]))
            episode_progress = EpisodeProgress(configured, progress, label, log_interval_seconds)
            preparation_started = perf_counter()
            episode_topology = (generate_topology(episode_config, progress=progress,
                                                 log_interval_seconds=log_interval_seconds)
                                if settings["randomize_episodes"] else topology)
            tasks, capacities, hashes = episode_inputs(episode_config)
            initial_graph = episode_topology.graph(0)
            expected_work = (episode_config["tasks"]["arrival_rate_per_slot"] /
                             episode_config["simulation"]["slot_seconds"] *
                             np.mean(episode_config["tasks"]["data_bits"]) *
                             np.mean(episode_config["tasks"]["cycles_per_bit"]))
            scenario.update(hashes, topology_signature=episode_topology.signature,
                            initial_connected=nx.is_connected(initial_graph),
                            initial_edges=initial_graph.number_of_edges(),
                            expected_global_cpu_rho=float(expected_work / capacities.sum()),
                            scenario_preparation_seconds=perf_counter() - preparation_started)
            scenario_path = output / "episode_scenarios" / ("episode_%06d.json" % (episode_count + 1))
            save_json(scenario_path, {**scenario, "resolved_config": episode_config,
                                     "cpu_capacities": capacities.tolist()})
            report("[SCENARIO] episode=%s root_seed=%s episode_seed=%s epoch=%.3fs hotspots=%s "
                   "expected_CPU_rho=%.3f initial_connected=%s | replay=%s" % (
                       episode_count + 1, scenario["root_seed"], seed, scenario["epoch_offset_seconds"],
                       scenario["hotspot_satellites"], scenario["expected_global_cpu_rho"],
                       scenario["initial_connected"], scenario_path))
            environment = LeoEnv(episode_config, episode_topology, tasks, capacities)
            observation, _ = environment.reset()
            fallback_count, choices = 0, 0
            diagnostics = {}
            while True:
                actions, batch, log_probability, value = agent.choose_action(observation)
                add_counts(diagnostics, agent.last_decision_metrics)
                next_observation, reward, terminated, truncated, info = environment.step(actions)
                episode_progress.step(info, reward)
                terminal = terminated or truncated
                # Next value is only needed at rollout cutoffs; full episodes
                # allow it to be filled from the following sampled state's value.
                buffer.append(Transition(batch, log_probability, value, reward, 0.0, terminal))
                if len(buffer.transitions) > 1 and not buffer.transitions[-2].terminal:
                    previous = buffer.transitions[-2]
                    buffer.transitions[-2] = Transition(previous.batch, previous.log_probability, previous.value,
                                                        previous.reward, value, False)
                fallback_count += sum(d.fallback for d in batch.decisions)
                choices += len(batch.decisions)
                if terminal:
                    break
                observation = next_observation
            episode_count += 1
            admitted = info["episode_metrics"]["all_admitted_task_count"]
            info["episode_metrics"]["mean_cost_per_admitted_task_s"] = (
                -info["episode_metrics"]["total_reward"] * config["reward"]["normalizer"] / admitted if admitted else None)
            timing = episode_progress.metrics()
            session_steps += timing["environment_steps"]
            collection_seconds += timing["episode_wall_seconds"]
            episodes.append({"episode": episode_count, "update": next_update, "seed": seed,
                             **scenario, "scenario_file": str(scenario_path),
                             "fallback_count": fallback_count, "decision_count": choices, **info["episode_metrics"],
                             **decision_metrics(diagnostics), **timing})
            save_csv(output / "episodes.csv", episodes)
            report("[EPISODE] episode=%s seed=%s | %s | FPS=%.2f env_steps=%s elapsed=%s fallback=%.2f%%" % (
                episode_count, seed, outcome_text(info["episode_metrics"]), timing["environment_fps"],
                timing["environment_steps"], duration_text(timing["episode_wall_seconds"]),
                100 * decision_metrics(diagnostics)["fallback_rate"]))
            report("[ROUTING] predicted_rejection=%.2f%% fallback=%.2f%% excluded=%.2f%% blocked_mass=%.4f "
                   "route_search_truncated=%.2f%%" % (
                       100 * episodes[-1]["predicted_invalid_action_rate"], 100 * episodes[-1]["fallback_rate"],
                       100 * episodes[-1]["destination_excluded_fraction"], episodes[-1]["blocked_probability_mass"],
                       100 * episodes[-1]["route_search_truncated_rate"]))
        report("[OPTIMIZE] update=%s/%s rollout_steps=%s | packed graph/task PPO optimization starting ..." % (
            next_update, settings["updates"], len(buffer)))
        optimize_started = perf_counter()
        metrics = agent.update(buffer, progress=progress, log_interval_seconds=log_interval_seconds)
        optimization_seconds = perf_counter() - optimize_started
        update = agent.update_count
        report("[PPO] update=%s/%s | loss=%s policy=%s value=%s entropy=%s KL=%s clip=%.2f%% grad=%s "
               "explained_var=%s optimizer_steps=%s KL_stop=%s elapsed=%s" % (
                   update, settings["updates"], metric_text(metrics["loss"]), metric_text(metrics["policy_loss"]),
                   metric_text(metrics["value_loss"]), metric_text(metrics["entropy_per_task"]),
                   metric_text(metrics["approximate_joint_kl"], 6), 100 * metrics["clip_fraction"],
                   metric_text(metrics["gradient_norm"]), metric_text(metrics["explained_variance_before_update"]),
                   metrics["optimizer_steps"], metrics["kl_early_stop"], duration_text(optimization_seconds)))
        report("[GRADIENT] encoder=%s self_encoder=%s actor_head=%s critic_head=%s graph_gate_mean=%s | norms before global clipping" % (
            metric_text(metrics["encoder_gradient_norm"]), metric_text(metrics["self_encoder_gradient_norm"]),
            metric_text(metrics["actor_head_gradient_norm"]), metric_text(metrics["critic_head_gradient_norm"]),
            metric_text(metrics["graph_gate_mean"])))
        report("[CRITIC] value_mean=%s value_std=%s return_mean=%s return_std=%s raw_value_MSE=%s "
               "normalized_value_MSE=%s mean_gradient_clip_scale=%s" % (
                   metric_text(metrics["value_prediction_mean"]), metric_text(metrics["value_prediction_std"], 6),
                   metric_text(metrics["return_mean"]), metric_text(metrics["return_std"]), metric_text(metrics["raw_value_loss"]),
                   metric_text(metrics["value_loss"]), metric_text(metrics["gradient_clip_scale"], 6)))
        validation_started = perf_counter()
        did_validate = False
        if update % settings["validation_every"] == 0 or update == settings["updates"]:
            did_validate = True
            rewards = []
            validation_rows = []
            for index, seed in enumerate(settings["validation_seeds"], 1):
                report("[VALIDATION] update=%s/%s seed=%s (%s/%s) starting ..." % (
                    update, settings["updates"], seed, index, len(settings["validation_seeds"])))
                validation_config = deepcopy(configured)
                validation_config["simulation"]["seed"] = seed
                row, _ = evaluate_policy(validation_config, topology, generate_task_trace(validation_config),
                                         generate_cpu_capacities(validation_config), agent, progress=progress,
                                         log_interval_seconds=log_interval_seconds, phase="VALIDATION")
                rewards.append(row["total_reward"])
                validation_rows.append(row)
                validation.append({"update": update, **row})
                report("[VALIDATION] seed=%s | %s | FPS=%.2f elapsed=%s" % (
                    seed, outcome_text(row), row["environment_fps"], duration_text(row["episode_wall_seconds"])))
            average_reward = float(np.mean(rewards))
            if best_reward is None or average_reward > best_reward:
                best_reward, best_update = average_reward, update
                agent.save(output / "best.pt", {"episode_count": episode_count,
                           "training_scenario_schema": SCENARIO_SCHEMA,
                           "best_validation_reward": best_reward, "best_update": best_update})
                report("[CHECKPOINT] New validation best: %s" % (output / "best.pt"))
            save_csv(output / "validation.csv", validation)
            mean_metrics = {}
            for key in ("total_reward", "success_rate", "mean_completion_delay_s", "p95_completion_delay_s",
                        "deadline_violation_rate", "route_failure_rate", "routing_rejection_rate", "censored_rate", "cpu_utilization",
                        "link_utilization", "mean_cost_per_admitted_task_s"):
                values = [row[key] for row in validation_rows]
                mean_metrics[key] = float(np.mean(values)) if all(v is not None for v in values) else None
            for key in ("completed_count", "task_count"):
                mean_metrics[key] = sum(row[key] for row in validation_rows)
            report("[VALIDATION MEAN] %s | best_update=%s best_reward=%s" % (
                outcome_text(mean_metrics), best_update, metric_text(best_reward)))
        validation_seconds = perf_counter() - validation_started if did_validate else 0.0
        checkpoint_started = perf_counter()
        training_state = {"episode_count": episode_count, "best_validation_reward": best_reward, "best_update": best_update,
                          "training_scenario_schema": SCENARIO_SCHEMA}
        agent.save(output / "last.pt", training_state)
        if update % settings["checkpoint_every"] == 0:
            agent.save(output / ("update_%05d.pt" % update), training_state)
        checkpoint_seconds = perf_counter() - checkpoint_started
        completed_updates += 1
        elapsed = perf_counter() - started
        eta = (settings["updates"] - update) * elapsed / completed_updates
        timing = {"update_wall_seconds": perf_counter() - update_started,
                  "collection_seconds": collection_seconds, "optimization_seconds": optimization_seconds,
                  "validation_seconds": validation_seconds, "checkpoint_seconds": checkpoint_seconds,
                  "rollout_fps": len(buffer) / max(collection_seconds, 1e-9),
                  "session_environment_steps": session_steps, "session_fps": session_steps / max(elapsed, 1e-9),
                  "eta_seconds": eta, **gpu_memory(agent.device)}
        updates.append({"update": update, "elapsed_seconds": elapsed, **metrics, **timing})
        save_csv(output / "updates.csv", updates)
        memory = gpu_memory(agent.device)
        memory_text = ("GPU_allocated=%.1fMiB GPU_reserved=%.1fMiB" % (
            memory["gpu_allocated_mib"], memory["gpu_reserved_mib"])) if memory else "GPU_used=no (CPU training)"
        report("[UPDATE DONE] %s/%s (%.1f%%) | rollout_FPS=%.2f session_FPS=%.2f session_steps=%s elapsed=%s ETA~%s "
               "%s | last=%s" % (
                   update, settings["updates"], 100 * update / settings["updates"], timing["rollout_fps"],
                   timing["session_fps"], session_steps, duration_text(elapsed), duration_text(eta),
                   memory_text, output / "last.pt"))
    save_json(output / "training_summary.json", {"updates": agent.update_count, "episodes": episode_count,
              "best_update": best_update, "best_validation_reward": best_reward,
              "elapsed_seconds": perf_counter() - started, "test_set_evaluated": False,
              "session_environment_steps": session_steps, "device": str(agent.device), "gpu_used": agent.device.type == "cuda"})
    report("[TRAIN COMPLETE] updates=%s episodes=%s best_update=%s best_reward=%s elapsed=%s | result_dir=%s" % (
        agent.update_count, episode_count, best_update, metric_text(best_reward), duration_text(perf_counter() - started), output))
    return agent
